Refactor JSON-RPC code - test_rpc_endpoints.py
drknzz/starknet-devnet pull request #1
Opened 2022-07-12 13:38 UTC by drknzz

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [ ] No linter errors
- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [ ] Linked the issues which this PR resolves
- [ ] Updated the tests
- [ ] All tests are passing

2022-07-12 14:20 UTC, cptartur requested changes
Couple of suggestions

2022-07-12 14:20 UTC, cptartur commented on test/rpc/conftest.py
> +"""
This docstring doesn't make much sense in this file

2022-07-12 14:20 UTC, cptartur commented on test/rpc/conftest.py
> +DECLARE_CONTENT = load_file_content("declare.json")
Have you verified if these work correctly now that rpc test are in a separate directory?

2022-07-12 14:20 UTC, cptartur commented on test/rpc/conftest.py
> +    return {**declare_info, **declare_tx}
Empty line missing at the end of the file

2022-07-12 14:20 UTC, cptartur commented on test/rpc/test_rpc_blocks.py
> +Tests RPC blocks.
```suggestion
Tests RPC blocks
```

2022-07-12 14:20 UTC, cptartur commented on test/rpc/test_rpc_endpoints.py
> +
I'd move these methods into separate, something like common/utils/whatever

2022-07-12 14:20 UTC, cptartur commented on test/rpc/test_rpc_storage.py
> +Tests RPC storage.
```suggestion
Tests RPC storage
```

2022-07-13 07:28 UTC, drknzz commented on test/rpc/conftest.py
> +DECLARE_CONTENT = load_file_content("declare.json")
Yes, the function uses path relative to the file it's defined in:

https://github.com/drknzz/starknet-devnet/blob/0501541a0772b082faf65030adab2cc95bd25f41/test/util.py#L410-L414

2022-07-13 07:35 UTC, cptartur commented on test/rpc/test_rpc_class.py
>  Tests RPC contract class.
```suggestion
Tests RPC contract class
```

2022-07-13 07:39 UTC, cptartur reviewed
Just a single overlooked full stop
Other than that, good work 👍

2022-07-13 07:39 UTC, cptartur commented on test/rpc/test_rpc_class.py
>  Tests RPC contract class.
```suggestion
Tests RPC contract class
```

2022-07-26 14:27 UTC, closed without merging