Feat/json rpc 0.2.0
drknzz/starknet-devnet pull request #15
Opened 2022-09-26 09:31 UTC by drknzz

`starknet_estimateFee`, which from v0.2.0 should accept all types of transactions
```
def estimate_fee(request: RpcBroadcastedTxn, block_id: BlockId)
```
currently does not comply with transactions other than invoke

2022-09-27 09:18 UTC, cptartur reviewed
Some of the tests are way too complicated: some of the repeating setup logic should be extracted to separate methods or fixtures so it's easier to review these tests. 

Also the use of `RPC_SUPPORTED_TX_VERSION` in tests named `..._v1` doesn't make much sense to me - if this constant was changed the tests would no longer be testing tx v1. This value should probably be hardcoded in these tests.

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_estimate_fee.py
> +        version=hex(SUPPORTED_RPC_TX_VERSION),
this should be hardcoded if tests is called `v1`

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_estimate_fee.py
> +        nonce=rpc_felt(0),
Shouldn't nonce be correctly set here?

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_misc.py
This tests is too complicated.

2022-09-27 09:18 UTC, cptartur commented on test/shared.py
> +SUPPORTED_RPC_TX_VERSION = 1
Same as above, why is it hardcoded to 1?

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        "nonce": rpc_felt(0),
What's the difference between rpc_felt and pad_zero?

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        "nonce": rpc_felt(0),
Are these checks safe in terms of test execution order? Is every tests using nonce run in separate devnet instance?

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +    )
Move this before asserts

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +    storage = gateway_call(
Same here

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        calldata=["0x0d", "0x038"],
Why is calldata hardoced here instead of `execute_calldata` like above?

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +
Shouldn't these be different than `0x0`?

2022-09-27 09:18 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
>  def test_add_declare_transaction(declare_content):
```suggestion
def test_add_declare_transaction_v1(declare_content):
```

2022-09-27 10:06 UTC, drknzz commented on starknet_devnet/blueprints/rpc/transactions.py
> +    address = request.get("contract_address", request.get("sender_address"))
The line
```
address = request.get("contract_address", request["sender_address"])
```
wouldn't work because the default value for `dict.get()` is evaluated before it is actually needed

so if `sender_address` does not exist in request, the line above would throw an error, despite `contract_address` being in request

It could be
```
address = request["contract_address"] if contract_address in request else request["sender_address"]
```

2022-09-27 10:07 UTC, drknzz commented on starknet_devnet/constants.py
> +SUPPORTED_RPC_TX_VERSION = 1
Only in tests testing the newest supported version

2022-09-27 10:13 UTC, drknzz commented on test/rpc/test_rpc_estimate_fee.py
> +        nonce=rpc_felt(0),
What do you mean by correctly?

2022-09-27 10:18 UTC, drknzz commented on test/rpc/test_rpc_misc.py
It's a slightly modified test from gateway to test rpc.
It's pretty beefy but the previous test for state update was huge as well.

2022-09-27 10:22 UTC, drknzz commented on test/rpc/test_rpc_transactions.py
> +        "nonce": rpc_felt(0),
`rpc_felt` takes an **integer** and returns a felt - hex starting with "0x0"
`pad_zero` takes a **string** which is already hex and changes it to have the prefix "0x0"

But it probably should be unified to `rpc_felt(value: Union[int, str]) -> Felt`

2022-09-27 10:23 UTC, drknzz commented on test/rpc/test_rpc_transactions.py
> +        "nonce": rpc_felt(0),
Every test is ran in a separate, isolated devnet instance.

2022-09-27 10:26 UTC, drknzz commented on test/rpc/test_rpc_transactions.py
> +
The asserts are taking a slice `[:3]` of each value, so only prefixes are checked here (i.e whether they are felts).

2022-09-27 10:36 UTC, drknzz commented on test/rpc/test_rpc_transactions.py
> +        calldata=["0x0d", "0x038"],
Since tx v1 does not have `entry_point_selector` and has `sender_address` instead of v0's `contract_address`, it has to go though account with the `contract_address` embedded into calldata (`execute_calldata` above).

Tx v0 does not need to go through account so it's not used here.

2022-09-28 08:46 UTC, Solpatium requested changes

2022-09-28 08:46 UTC, Solpatium commented on starknet_devnet/blueprints/rpc/call.py
>          return result
Nitpick, but you can return this list right away

2022-09-28 08:46 UTC, Solpatium commented on starknet_devnet/blueprints/rpc/structures/payloads.py
> +        return _nonces
It seems you don't change _nonces at all. I suggest replacing this with list comprehension. Also some tests for this case would be nice.

2022-09-28 08:46 UTC, Solpatium commented on test/rpc/conftest.py
> +from ..util import load_file_content
Why are relative imports used?

2022-09-28 08:46 UTC, Solpatium commented on test/rpc/test_rpc_class.py
> +from .rpc_utils import rpc_call
Why are relative imports mixed with absolute

2022-09-28 09:02 UTC, cptartur commented on test/rpc/test_rpc_estimate_fee.py
> +        nonce=rpc_felt(0),
I think so. If we are using an account anyways.

2022-09-28 09:04 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        calldata=["0x0d", "0x038"],
Perhaps this should be abstracted to a helper method then? It's not clear why these values are hardcoded and it makes maintaining this tests much more complicated.

2022-09-28 09:05 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +
Could a helper be created for this? Like `assert is_rpc_felt(receipt["class_hash"])` or something along the lines.

2022-09-28 09:06 UTC, cptartur commented on test/rpc/test_rpc_misc.py
Is there a way to simplify it even a little?

2022-09-28 09:07 UTC, cptartur commented on starknet_devnet/blueprints/rpc/transactions.py
> +    address = request.get("contract_address", request.get("sender_address"))
Hmm, it is more code, but I'm not really sure about nesting `.get()` calls like this.

@Solpatium what do you think?

2022-09-28 12:46 UTC, merged