Support for RPC API Specification v0.1.0
drknzz/starknet-devnet pull request #7
Opened 2022-08-03 12:46 UTC by drknzz

## Usage related changes

All of the methods from the latest [RPC API Specification v0.1.0](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.1.0) are implemented and tested with the following exceptions:
- starknet_pendingTransactions
- starknet_syncing
- starknet_getEvents
- starknet_getNonce
- starknet_estimateFee - no tests
## Checklist:

- [ ] No linter errors
- [ ] Performed a self-review of the code
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [ ] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing

2022-08-04 10:01 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +#     }
👁️

2022-08-04 10:03 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +        raise RpcError(code=-1, message="Calls with block_id != 'latest' are not supported currently.")
This is used in multiple places. Could this be extracted to another method like `assert_block_id_is_latest` or something along the lines?

2022-08-04 10:04 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +    fee_response = await state.starknet_wrapper.calculate_actual_fee(invoke_function)
What is the return type of this method?

2022-08-04 10:05 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +    gas_usage: int
I'm not sure if it makes sense to define this TypedDict. It's used only as the type annotation for `rpc_type_estimate` input, but nowhere it's actually verified that the parameter passed to this metod actually conforms to this type.

2022-08-04 10:06 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +    )
Why not use make_invoke_function that should be already defined in the rpc blueprint?

2022-08-04 10:06 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +        raise RpcError(code=-1, message="Calls with block_id != 'latest' are not supported currently.")
Same as above

2022-08-04 10:08 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +async def pending_transactions() -> List[Union[RpcInvokeTransaction, RpcDeclareTransaction, RpcDeployTransaction]]:
Maybe define this at the top of file like `Transactions = Union[RpcInvokeTransaction, RpcDeclareTransaction, RpcDeployTransaction]`?

2022-08-04 10:10 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +        "status": block.status.name,
I'm not sure if using this value directly is a good idea. I believe that the possible statues in cairo-lang are different than these in the rpc. If that's the case there should be a helper method mapping these types.

2022-08-04 10:21 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +def rpc_transaction(transaction: TransactionSpecificInfo) -> Union[RpcInvokeTransaction, RpcDeclareTransaction, RpcDeployTransaction]:
As above, use declared union

2022-08-04 10:22 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +    block_number: BlockNumber
Does it make sense to declare a dataclass for pending tx if these are not possible on devnet?

2022-08-04 10:25 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
>      statusData: Optional[str]
I believe it's now correctly named `status_data` in the specs so it needs to be updated here and in tests.

2022-08-04 10:26 UTC, cptartur commented on test/rpc/test_rpc_blocks.py
> +    }
What's the point of having this map?

2022-08-04 10:27 UTC, cptartur commented on test/rpc/test_rpc_blocks.py
> +        "starknet_getBlockWithTxHashes", params={"block_id": block_id_map[block_id]}
Would it be possible to now do a `assert resp = {}` or do we still have to compare key by key?

2022-08-04 10:28 UTC, cptartur commented on test/rpc/test_rpc_blocks.py
> +    }
Same as above

2022-08-04 10:29 UTC, cptartur commented on test/rpc/test_rpc_blocks.py
> +        "constructor_calldata": block_tx["constructor_calldata"],
Shouldn't calldata also be pedded zero? I believe the transaction we're using doesn't actually have any constructor calldata which means we aren't actually testing if our serialization is correct here. Perhaps this tx could be changed (preffered) or we should add additional tests just for the calldata.

2022-08-04 10:31 UTC, cptartur commented on test/rpc/test_rpc_blocks.py
> +        "type": block_tx["type"],
I don't think this assertion is universally correct.  Transactions in rpc are `DECLARE, DEPLOY, INVOKE` and I believe in cairo lang it's `DECLARE, DEPLOY, INVOKE_FUNCTION`. Please verify we're using correct transaction types here and in the rpc.

2022-08-04 10:35 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +        "type": transaction.tx_type.name,
You are assigning the wrong type here, type in the rpc is `INVOKE` but in the cairo-lang it's `INVOKE_FUNCTION`.
It'd be better to hardcode transaction type here since it's method only for handling invoke transactions. Similarly, this should be changed in `rpc_declare_transaction` and `rpc_invoke_transaction`.

2022-08-04 10:37 UTC, cptartur commented on test/rpc/test_rpc_call.py
> +                "entry_point_selector": hex(get_selector_from_name("xxxxxxx")),
Instead of repeating ourselves here, we should use pytest.mark.parametrize.

2022-08-04 10:38 UTC, cptartur commented on test/rpc/test_rpc_class.py
We're using hardcoded values before. I think it'd be better to inject them through fixture.

2022-08-04 10:41 UTC, cptartur commented on test/rpc/test_rpc_class.py
Also perhaps we could improve the check for the `contract_class["program"]`. Something like assert it's actually decodable and the result of decoding is a proper alphanumeric string (so no weird artefacts like ĺĻī in string)

2022-08-04 10:42 UTC, cptartur commented on test/rpc/test_rpc_misc.py
>      storage = gateway_call("get_storage_at", contractAddress=contract_address, key=get_storage_var_address("balance"))
Maybe this should be move to the top of the tests so it's less confusing what's going on?

2022-08-04 10:47 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        "type": block_tx["type"],
Same as above

2022-08-04 10:50 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        "max_fee": block_tx["max_fee"],
It should be padded zero

2022-08-04 10:50 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +        "constructor_calldata": block_tx["constructor_calldata"],
Calldata should be padded zero

2022-08-04 10:51 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +                "block_hash": INCORRECT_GENESIS_BLOCK_HASH
What is this constant?

2022-08-04 11:55 UTC, drknzz commented on starknet_devnet/blueprints/rpc.py
> +        "version": hex(0x0),
From what I can see, only `DeclareSpecificInfo` has `version` field.

2022-08-04 12:32 UTC, drknzz commented on starknet_devnet/blueprints/rpc.py
> +    method, args, message_id = parse_body(flaskRequest.json)
Linter threw warnings about renaming a variable from outer scope (request from flask), since there are methods that use a `request` argument and I wanted to stick to variable names from RPC specification.

2022-08-04 13:13 UTC, drknzz commented on starknet_devnet/blueprints/rpc.py
> +    fee_response = await state.starknet_wrapper.calculate_actual_fee(invoke_function)
It is the following dict:

```
{
    "overall_fee": tx_fee,
    "unit": "wei",
    "gas_price": gas_price,
    "gas_usage": gas_usage,
}
```

2022-08-04 14:14 UTC, drknzz commented on test/rpc/test_rpc_blocks.py
> +    }
So the parametrization in the test is easier to read as it is ["hash", "number", "tag"], instead of a list of long arguments. Should we just put the arguments directly into the parametrization list?

2022-08-04 16:48 UTC, drknzz commented on test/rpc/test_rpc_call.py
> +                "entry_point_selector": hex(get_selector_from_name("xxxxxxx")),
From what I see, there are different errors expected in each test. Can we somehow parametrize that as well?

2022-08-04 16:55 UTC, drknzz commented on test/rpc/test_rpc_transactions.py
> +                "block_hash": INCORRECT_GENESIS_BLOCK_HASH
It's a constant from master branch, it already was there in this test.

2022-08-04 17:02 UTC, drknzz commented on starknet_devnet/blueprints/rpc.py
> +    method, args, message_id = parse_body(flaskRequest.json)
And I actually changed it now to flask_request

2022-08-05 09:01 UTC, drknzz commented on test/rpc/test_rpc_class.py
The result of decoding contract_class["program"] is a dictionary. Should we validate the whole dict?

2022-08-05 09:34 UTC, war-in commented on starknet_devnet/blueprints/rpc.py
> +    transactions: Union[List[str], List[dict]]
We could change the typing of transactions: Union[List[Felt], List[Transaction]], where Transaction is Union[RpcInvokeTransaction, RpcDeclareTransaction, RpcDeployTransaction]

2022-08-05 09:41 UTC, war-in commented on starknet_devnet/blueprints/rpc.py
> +        "version": hex(0x0),
Yes, it is not available

2022-08-05 09:42 UTC, war-in commented on starknet_devnet/blueprints/rpc.py
> +        "nonce": rpc_felt(transaction.nonce),
Nonce is not optional here

2022-08-05 10:19 UTC, Solpatium requested changes

2022-08-05 10:19 UTC, Solpatium commented on starknet_devnet/blueprints/rpc.py
> +Felt = str
If this is hex then maybe naming it Hex would be a better name.

2022-08-05 10:19 UTC, Solpatium commented on test/rpc/test_rpc_blocks.py
> +    }
Yes, add there directly. You can use tuples and define each one in new line.

2022-08-05 10:19 UTC, Solpatium commented on test/rpc/test_rpc_call.py
> +                "entry_point_selector": hex(get_selector_from_name("xxxxxxx")),
Yes, we can parametrize them as well by using tuples.

2022-08-05 10:23 UTC, drknzz commented on starknet_devnet/blueprints/rpc.py
> +PROTOCOL_VERSION = "0.9.1"
This method is being removed in future specification version.
But it was supposed to be the starknet version.

2022-08-05 10:55 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +        "version": hex(0x0),
I guess we can keep them hardcoded for the time being but perhaps it'd be a good idea to include a comment about this here and in the PR message once we create it. So we don't forget to update it in the next cairo-lang version.

2022-08-05 10:55 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +        "version": hex(0x0),
Same as above

2022-08-05 13:22 UTC, cptartur commented on test/rpc/test_rpc_class.py
If it's possible to do nicely, I guess we should do that.

2022-08-05 13:23 UTC, cptartur commented on test/rpc/test_rpc_transactions.py
> +                "block_hash": INCORRECT_GENESIS_BLOCK_HASH
Alright, let's keep it then.

2022-08-05 13:23 UTC, cptartur commented on starknet_devnet/blueprints/rpc.py
> +PROTOCOL_VERSION = "0.9.1"
We should remove it now i think

2022-08-10 10:38 UTC, Solpatium commented on test/rpc/rpc_utils.py
> +    return "0x0" + felt.lstrip("0x")
`lstrip` is probably not what you need, it removes all characters specified in the string. This means You want replace() with count=1. This makes if unnecessary. Please note that is will work differently for values like `0x000001` - lstrip removes all 0s, replace("0x0") won't.

2022-10-24 07:47 UTC, closed without merging